---

# ГЛОБАЛЬНЫЕ ПЕРЕМЕННЫЕ:
GLOBAL:
  api_version: "2"
  
  # Домен который будем использовать для кластера
  domain: ".che.local"
  
  # PHP:
  #   Доступные, протестированные переменные:
  #   5.4, 5.6, 7.1, 7.2, 7.3, 7.4, 8.0
  php_version: 7.4      
  
  # MySQL:
  #   Доступные, протестированные переменные:
  #   mysql57, mysql8, mariadb103, mariadb104, mariadb105, mariadb106
  mysql_version: mysql8  
  
  # VAGRANT PROVIDER:
  #   Доступные, протестированные переменные:
  #     Docker              - docker
  #     Hyper-V             - hyperv
  #     VirtualBox          - virtualbox
  #     VMWare Fusion       - vmware_fusion
  #     VMWare Workstation  - vmware_workstation        
  vagrant_provider: virtualbox
  
  # ЕДИНЫЙ ОБРАЗ СИСИТЕМЫ ДЛЯ ВСЕХ ВИРТУАЛЬНЫХ МАШИН: 
  #   Доступные, протестированные переменные:
  #     ubuntu/focal64 (20220724.0.0)
  box: "ubuntu20-04"
  #box_version: "20220724.0.0"
  #   Следующий параметр, если true, то на всех виртуальных машинах будет использоваться только вышеуказанный образ системы
  #   Если необходимо для каждой ВМ использовать свой образ, переопределить переменную как false
  #   и в настройках каждой из ВМ указать желаемый образ.
  box_usage: true


  #   config.vm.box = "**"
  USING_LOCAL_BOX_FILE: false
  LOCAL_BOX_URL: 
    -  "file://../../vagrant-boxes/xxxxx.box"
    -  "http://x.x.x.x//vagrant-boxes/xxxxx.box"
  
...
